### ISSUE TITLE
Default post-renewal script content not especially useful for everyone 

### ISSUE THREAD

**Issue by chris968** [usegalaxy-eu/ansible-certbot#14]
I like the idea to have the possibility to write some custom post-renewal scripts but I don't understand the purpose of this code especially if you renew multiple domains certificates as only the first one will be copied.

Maybe adding some condition here will help create a cleaner scripts for those who don't want this part ?

```
# Chai
cp {{ certbot_letsencrypt_dir }}/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/fullchain.pem /etc/ssl/certs/fullchain.pem
chmod 644           /etc/ssl/certs/fullchain.pem
chown root:{{ certbot_ssl_group | default('') }} /etc/ssl/certs/fullchain.pem
# Cert
cp {{ certbot_letsencrypt_dir }}/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/cert.pem      /etc/ssl/certs/cert.pem
chmod 644           /etc/ssl/certs/cert.pem
chown root:{{ certbot_ssl_group | default('') }} /etc/ssl/certs/cert.pem
# Privkey
cp {{ certbot_letsencrypt_dir }}/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/privkey.pem   /etc/ssl/private/privkey.pem
chmod 640           /etc/ssl/private/privkey.pem
chown root:{{ certbot_ssl_group | default('') }} /etc/ssl/private/privkey.pem

**Comment by hexylena** [comment]
So that doesn't copy the first certificate: it copies the **only** certificate. This role does not really support generating multiple, separate certificate files (unless you run the role multiple times which isn't a supported use case.)

When you have multiple `certbot_domains`, the first one is taken as the main name on the cert, and the subsequent ones are all SANs. (This is intentional, we really only want one certificate file, that answers to every domain that's relevant for us.) When certbot generates that certificate on disk, it uses the same logic, and names the file after the primary domain name on the cert, while the other domains are all in metadata.

So unless you're trying to generate multiple files on disk, making multiple requests to LE, then this works fine.

**Comment by chris968** [comment]
I didn't test it but the following line of the "Request certificate" task will actually concatenate all `certbot_domains` list entries in someting like `-d test1.dom.org,test2.dom.org`

`-d {{ ','.join(certbot_domains) }}`

**Comment by hexylena** [comment]
yes, that is correct for requesting a single cert with additional names as SANs


````
  -d DOMAIN, --domains DOMAIN, --domain DOMAIN
                        Domain names to apply. For multiple domains you can
                        use multiple -d flags or enter a comma separated list
                        of domains as a parameter. The first domain provided
                        will be the subject CN of the certificate, and all
                        domains will be Subject Alternative Names on the
                        certificate. The first domain will also be used in
                        some software user interfaces and as the file paths
                        for the certificate and related material unless
                        otherwise specified or you already have a certificate
                        with the same name. In the case of a name collision it
                        will append a number like 0001 to the file path name.
                        (default: Ask)
```

**Comment by chris968** [comment]
My bad misreading the documentation, however it might be useful to be able to generate multiple certificats from a domain lists. 
I still don't get the point copying files elsewhere, in my case I just need to put extra lines through `{{ certbot_post_renewal }}` to concatenate private key and cert chain in proper order to use it with haproxy, but well, it work like this.

**Comment by hexylena** [comment]
> however it might be useful to be able to generate multiple certificats from a domain lists

yes, agreed. Please see #11, we think that's how we'll implement this feature.

> I still don't get the point copying files elsewhere

This is mostly done because we have the case where different services, running as different users, need to access the certificates. And instead of creating a group, and making sure all those processes are running under the same group, it's a lot easier for us to just duplicate the certificate with different permissions.

**Comment by chris968** [comment]
> yes, agreed. Please see #11, we think that's how we'll implement this feature.

Having the possibility to choose generate SNI or multiple certificats will be a good addition, the role should loop the certificat request task through a domain list for multiple certificats, probably not too much changes involved.

> This is mostly done because we have the case where different services, running as different users, need to access the certificates. And instead of creating a group, and making sure all those processes are running under the same group, it's a lot easier for us to just duplicate the certificate with different permissions.

Ok, I get the purpose but the code should be modified if multiple certificates are generated, it don't work in my particular case because of haproxy.
